---

- name: Set up postgres
  hosts: localhost
  connection: local
  remote_user: ubuntu
  become: true
  gather_facts: false
  vars:
    - postgres_root_user: ubuntu
    - postgres_root_pass: mypassword
    - postgres_db_name: my_db
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
  #   - name: Allow user sudo without a password
  #     lineinfile:
  #       path: /etc/sudoers
  #       state: present
  #       line: 'circleci ALL=(ALL) NOPASSWD: ALL'
  #       validate: 'visudo -cf %s'

  roles:
    - setup-postgres
    # - install-git

  handlers:
      # Set up handlers
      # include_tasks: postgres_handlers.yml
      - name: Restart Postgresql
        systemd:
          name: postgresql
          state: restarted

      - name: Start Postgresql
        systemd:
          name: postgresql
          state: started

      - name: Stop Postgresql
        systemd:
          name: postgresql
          state: stopped

      - name: Enable Postgresql
        systemd:
          name: postgresql
          enabled: yes