---

- name: Set up Nginx
  hosts: web
  # connection: local
  remote_user: ubuntu
  become: true
  gather_facts: false

  pre_tasks:
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - setup-nginx
    - configure-prometheus-node-exporter
    - install-awscli