---

- name: Set up postgres
  hosts: private_server
  remote_user: ubuntu
  become: true
  gather_facts: false
  vars:
    - postgres_root_user: ubuntu
    - postgres_root_pass: mypassword
    - postgres_db_name: my_db
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # pre_tasks:
  #   - name: Allow user sudo without a password
  #     lineinfile:
  #       path: /etc/sudoers
  #       state: present
  #       line: 'circleci ALL=(ALL) NOPASSWD: ALL'
  #       validate: 'visudo -cf %s'

  roles:
    - setup-postgres

  handlers:
      # Set up handlers
      # include_tasks: postgres_handlers.yml
      - name: Restart Postgresql
        systemd:
          name: postgresql
          state: restarted

      - name: Start Postgresql
        systemd:
          name: postgresql
          state: started

      - name: Stop Postgresql
        systemd:
          name: postgresql
          state: stopped

      - name: Enable Postgresql
        systemd:
          name: postgresql
          enabled: yes