# - name: Install Nginx
#   become: true
#   apt:
#     name: nginx
#     state: latest
#     update_cache: yes

# - name: start nginx
#   become: true
#   shell: |
#     systemctl start nginx
#     systemctl status nginx
#   register: nginx_start_message

# - name: Show nginx start message
#   debug:
#     msg: "{{ nginx_start_message.stdout_lines }}"

# - name: Copy config files
#   become: true
#   copy:
#     src: app
#     dest: /etc/nginx/sites-available/

    
# - name: Add symlinks
#   become: true
#   file:
#     src: /etc/nginx/sites-available/app
#     dest: /etc/nginx/sites-enabled/app
#     state: link

# - name: start nginx
#   become: true
#   shell: |
#     systemctl restart nginx

# - name: Test connection
#   shell: curl http://localhost
#   register: test_output

# - name: Show connection test output
#   debug:
#     msg: "{{ test_output.stdout_lines }} or {{ test_output.stderr_lines }}"

- name: Install venv
  apt:
    name: python3-venv
    state: latest
    update_cache: yes

- name: Show working directory
  shell: |
    pwd
    printenv
  register: working_dir

- name: workdir
  debug:
    msg: "{{ working_dir.stdout_lines }}"


- name: Configure flask app
  shell: |
    python3 -m venv venv
    ls -a
    # source venv/bin/activate
    # cd simple_flask_app
    # pip install -r requirements.txt
    # python3 app.py
  register: app_config

- name: Show app config
  debug:
    msg: "{{ app_config.stderr_lines }}"

