- name: Install Nginx
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: start nginx
  shell: |
    sudo systemctl start nginx
  register: nginx_start_message

- name: Show nginx start message
  debug:
    msg: "{{ nginx_start_message.stdout_lines }}"

# - name: Copy config files
#   become: true
#   copy:
#     src: app
#     dest: /etc/nginx/sites-available/
    
# - name: Add symlinks
#   become: true
#   file:
#     src: /etc/nginx/sites-available/app
#     dest: /etc/nginx/sites-enabled/app
#     state: link

- name: start nginx
  become: true
  shell: |
    systemctl restart nginx
  register: nginx_restart_message

- name: Show nginx restart message
  debug:
    msg: "{{ nginx_restart_message.stdout_lines }}"

- name: Test connection
  shell: curl -X http://localhost
  register: test_output

- name: Show connection test output
  debug:
    msg: "{{ test_output.stdout_lines }}"
